version: "3.7"

services:

  rethinkdb:
    image: "rethinkdb:2.4.1"
    restart: "always"
    volumes:
      - "rethinkdb_data:/data"
    networks:
      - "public"
    ports:
      - "8080:8080/tcp"
      - "28015:28015/tcp"

  rabbitmq:
    image: "rabbitmq:3.8.18-management-alpine"
    restart: "always"
    environment:
      RABBITMQ_ERLANG_COOKIE: "erlang_cookie_secret"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "changeme"
    networks:
      - "public"
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"


volumes:

  rethinkdb_data:

networks:

  public:
    name: public
