version: "3.7"

services:

  rethinkdb:
    image: "rethinkdb:2.4.1"
    restart: "always"
    volumes:
      - "rethinkdb_data:/data"
    networks:
      - "public"
    ports:
      - "8080:8080/tcp"
      - "28015:28015/tcp"

volumes:

  rethinkdb_data:

networks:

  public:
    name: public
